[project]
name = "asteroids"
version = "0.1.0"
description = "Bootdev's Pygame clone of the classic Asteroids game"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygame==2.6.1",
]
